#!/bin/bash

COMPONENTS=$(ls -D -1 ./src/components)

sed -i '1,/-- autogenerated do not edit after this line --/!d' readme.md
echo >> readme.md

for C in $COMPONENTS; do
  echo "* [${C}](./src/components/${C}/readme.md)" >> readme.md
  echo >> readme.md
done
