#!/usr/bin/env node

const fs = require("fs")
const join = require("path").join

const COMPONENT_PATH = join(__dirname, "../src/components")
const README_FILE = join(__dirname, "../readme.md")
const REGEX = new RegExp(".*--- autogenerated do not edit after this line ---.*")

console.log("[info]  Updating readme file...")

const componentList = fs.readdirSync(COMPONENT_PATH)

const links = componentList.map((comp) => {
  return (fs.existsSync(`${COMPONENT_PATH}/${comp}/readme.md`))
    ? `* [${comp}](src/components/${comp}/readme.md)`
    : `* ${comp} (missing readme!!!)`
})

const readme = fs.readFileSync(README_FILE)

let newReadme = ""
for (line of readme.toString().split("\n")) {
  newReadme += line + "\n"
  if (line.match(REGEX) !== null) { break }
}

newReadme += `
## Components

> **Note:** Do not add your component here manually.
> To generate this component list run &nbsp; \`$ npm run build\`

${links.join("\n")}
`
fs.writeFileSync(README_FILE, newReadme)

console.log("[info]  done!")
process.exit(0)
