#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=5ef4b89cd0f2f9a12c5afeae4068493f4442b7e1
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2
APP_DIR="$(dirname "$GIT_DIR")"

$APP_DIR/node_modules/.bin/gulp build
$APP_DIR/node_modules/.bin/gulp test

exit $?
